### ISSUE TITLE
error in windows

### ISSUE THREAD

**Issue by Xray22336** [macronut/phantomsocks#72]
When I launch this software 
`.\phantomsocks.exe -log 1`
It outputs 
```
panic: runtime error: slice bounds out of range [:5031251891146] with capacity 1500

goroutine 7 [running]:
github.com/macronut/godivert.(*WinDivertHandle).Recv(0xc00009c030)
        C:/Users/henry/go/pkg/mod/github.com/macronut/godivert@v0.0.0-20220121081532-78e5dd672daf/windivert.go:141 +0x19f
github.com/macronut/phantomsocks/phantomtcp.connectionMonitor(0x0?)
        D:/1/test/phantomsocks-main/phantomtcp/windivert.go:81 +0x187
created by github.com/macronut/phantomsocks/phantomtcp.ConnectionMonitor in goroutine 19
        D:/1/test/phantomsocks-main/phantomtcp/windivert.go:295 +0xd8
```

**Comment by Xray22336** [comment]
I built this software using
`go build -tags windivert`

**Comment by macronut** [comment]
Download WinDivert from https://github.com/basil00/Divert/releases/v1.4.3
