### ISSUE TITLE
panic: runtime error: slice bounds out of range [:7954192989596] with capacity 1500

### ISSUE THREAD

**Issue by forodo** [Macronut/phantomsocks#8]
编译出来了，WinDivert 所有文件也和 phantomsocks.exe 放在一起了，但运行的时候却报错了，这个错误我就不知道该怎么解决了。。。
```
C:\phantomsocks>phantomsocks -socks 127.0.0.1:1080
Socks: 127.0.0.1:2080
panic: runtime error: slice bounds out of range [:7954192989596] with capacity 1500

goroutine 22 [running]:
github.com/macronut/godivert.(*WinDivertHandle).Recv(0xc000c68020, 0x7, 0x10000, 0xc000c68020)
        C:/Golang/pkg/mod/github.com/macronut/godivert@v0.0.0-20200223163208-e0ee08361ab9/windivert.go:141 +0x266
github.com/macronut/phantomsocks/phantomtcp.connectionMonitor(0xc00119a100)
        C:/Golang/pkg/mod/github.com/macronut/phantomsocks@v0.0.0-20220111034652-4ef363a0b95e/phantomtcp/windivert.go:40 +0x125
created by github.com/macronut/phantomsocks/phantomtcp.ConnectionMonitor
        C:/Golang/pkg/mod/github.com/macronut/phantomsocks@v0.0.0-20220111034652-4ef363a0b95e/phantomtcp/windivert.go:254 +0x105
```
试了另一个 redir 方式启动也报错这个，需要我提供哪些信息？

- **Go 版本**：v1.16
- **WinDivert 版本**：2.2.0-A x86_64
- **Windows 版本**：Win10 21H1 64位（编译的也是 64 位）
- **default.conf 文件**：默认内容

**Comment by Macronut** [comment]
https://github.com/williamfhe/godivertWinDivert 1.4

**Comment by forodo** [comment]
啊，试了下 v1.4.3 还真可以了。。。奇怪昨天后续测试这个版本却不行，可能是没重启的原因吧。。。谢啦~

另外，想问一下这么多 methods 模式，我该如何判断各个网站该用哪种模式？还是说 w-md5 就能解决大部分网站了~

总之，感谢大佬开发这么好的工具，完全满足了我局部使用的需求😁~

**Comment by forodo** [comment]
又研究了下，发现上面我原来测试的有问题。。。
重新测试后发现，`-install` 安装后去启动实际是成功了，但是没有监听任何端口。。。不知道该怎么用。。。
我该如何以 `-socks 127.0.0.1:1080` 方式去启动该服务？
